(() => {
  const waitForApp=()=>typeof sb!=='undefined'&&typeof S!=='undefined'&&document.querySelector('#adminView');
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const isAfacon=()=>norm(S.aName).includes('afacon');
  const isInternalOnlySeries=name=>{const n=norm(name);return n.includes('serie primera')||n.includes('primera adulta')||n.includes('segunda serie')};

  function ensurePanels(){
    const main=document.querySelector('#adminView main');if(!main)return;
    if(!document.querySelector('#p-club')){
      const s=document.createElement('section');s.id='p-club';s.className='panel hidden';
      s.innerHTML=`<div class="section-title"><div><h2>Mi club</h2><p class="muted">Personaliza la identidad de tu equipo.</p></div></div><div class="card" style="max-width:650px"><div id="clubLogoBox" style="display:flex;gap:18px;align-items:center;flex-wrap:wrap"></div><form id="clubLogoForm" style="display:grid;gap:12px;margin-top:16px"><label>Logo del club<input id="clubLogoFile" type="file" accept="image/jpeg,image/png,image/webp" required></label><button class="primary">Subir logo de mi club</button></form><div id="clubLogoMsg" class="msg"></div></div>`;
      main.appendChild(s);s.querySelector('#clubLogoForm').onsubmit=uploadClubLogo;
    }
  }
  function activateExtra(id){document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));document.querySelector('#p-'+id)?.classList.remove('hidden');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===id));if(id==='club')renderClubPanel()}
  function patchNav(){const nav=document.querySelector('#nav');if(!nav||!S.u)return;nav.querySelector('[data-p="reports"]')?.remove();if(S.u.role==='team_admin'&&!nav.querySelector('[data-p="club"]')){const b=document.createElement('button');b.dataset.p='club';b.textContent='Mi club / Logo';b.onclick=()=>activateExtra('club');nav.appendChild(b)}}
  function renderClubPanel(){const box=document.querySelector('#clubLogoBox');if(!box||S.u?.role!=='team_admin')return;const team=S.teams.find(t=>t.id===S.u.team_id);if(!team){box.innerHTML='<div class="empty">No se encontró tu club.</div>';return}const img=team.logo_url?`<img src="${team.logo_url}" alt="Logo ${team.name}" style="width:110px;height:110px;object-fit:contain;background:#eef4ef;border:1px solid #93a995;border-radius:16px;padding:8px">`:`<div style="width:110px;height:110px;display:grid;place-items:center;border:2px dashed #93a995;border-radius:16px;font-size:2.5rem">⚽</div>`;box.innerHTML=`${img}<div><h3 style="margin:0 0 6px">${team.name}</h3><p class="muted" style="margin:0">JPG, PNG o WebP · máximo 5 MB.</p></div>`}
  async function uploadClubLogo(e){e.preventDefault();const msg=document.querySelector('#clubLogoMsg'),file=document.querySelector('#clubLogoFile')?.files?.[0];try{if(S.u?.role!=='team_admin'||!S.u.team_id)throw Error('Solo un administrador de club puede cambiar este logo.');if(!file)throw Error('Selecciona una imagen.');if(file.size>5*1024*1024)throw Error('El logo no puede superar 5 MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Formato no permitido. Usa JPG, PNG o WebP.');msg.textContent='Subiendo logo...';msg.className='msg';const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,''),path=`${S.u.team_id}/logo-${Date.now()}.${ext}`;const {error:upErr}=await sb.storage.from('team-logos').upload(path,file,{cacheControl:'3600'});if(upErr)throw upErr;const {data:urlData}=sb.storage.from('team-logos').getPublicUrl(path),url=urlData.publicUrl;const {error:dbErr}=await sb.rpc('set_my_team_logo',{p_logo_url:url});if(dbErr)throw dbErr;const team=S.teams.find(t=>t.id===S.u.team_id);if(team)team.logo_url=url;msg.textContent='Logo actualizado correctamente.';msg.className='msg ok';renderClubPanel();e.target.reset()}catch(err){msg.textContent=err?.message||'No se pudo subir el logo.';msg.className='msg error'}}

  function installAdminGate(){const adminBtn=document.querySelector('#adminLoginBtn'),ownerBtn=document.querySelector('#ownerLoginBtn'),loginForm=document.querySelector('#loginForm'),backBtn=document.querySelector('#backPublic');if(adminBtn)adminBtn.onclick=()=>document.querySelector('#loginModal')?.classList.remove('hidden');if(ownerBtn)ownerBtn.onclick=()=>document.querySelector('#loginModal')?.classList.remove('hidden');if(loginForm)loginForm.addEventListener('submit',()=>sessionStorage.setItem('adminGate','1'),true);if(backBtn)backBtn.onclick=async()=>{const aid=S.a;if(aid)localStorage.setItem('publicAssociation',aid);sessionStorage.removeItem('adminGate');await sb.auth.signOut();S.u=null;await startPublic()};setTimeout(async()=>{const {data:{session}}=await sb.auth.getSession();if(session&&sessionStorage.getItem('adminGate')!=='1'){await sb.auth.signOut();S.u=null;await startPublic()}},500)}
  function installManualVenue(){const form=document.querySelector('#fixtureForm'),old=document.querySelector('#fVenue');if(!form||!old||old.dataset.manualVenue==='1')return;const label=old.closest('label');if(!label)return;const input=document.createElement('input');input.id='fVenue';input.type='text';input.placeholder='Ej: Estadio Municipal, Cancha El Bosque, Sin cancha fija';input.autocomplete='off';input.dataset.manualVenue='1';old.replaceWith(input);label.firstChild.textContent='Cancha / recinto';form.onsubmit=async e=>{e.preventDefault();if(!canSchedule())return flash('#fixtureMsg','No tienes permiso');if(!document.querySelector('#fCompetition').value)return flash('#fixtureMsg','Primero debes tener una liga creada para esta asociación');if(document.querySelector('#fHome').value===document.querySelector('#fAway').value)return flash('#fixtureMsg','Local y visita deben ser distintos');const {data,error}=await sb.rpc('create_club_fixture_named_venue',{p_competition_id:document.querySelector('#fCompetition').value,p_home_team_id:document.querySelector('#fHome').value,p_away_team_id:document.querySelector('#fAway').value,p_venue_name:document.querySelector('#fVenue').value.trim()||null,p_fixture_date:document.querySelector('#fDate').value,p_round_number:document.querySelector('#fRound').value?Number(document.querySelector('#fRound').value):null});flash('#fixtureMsg',error?.message||(data?'Fecha programada correctamente':'Fecha programada'),!error);if(!error){form.reset();syncFixtureClubs();installManualVenue();await loadFixtures()}}}

  function seriesQualificationStatus(pos,seriesName,competitionName){if(isInternalOnlySeries(seriesName))return pos===1?'🏅 Campeón de serie':'—';if(isAfacon()){const c=norm(competitionName);if(c.includes('liga a')){if(pos===1)return '🏆 Copa Regional';if(pos===2||pos===3)return '⚔️ Liguilla';return '—'}if(c.includes('liga b')){if(pos===1||pos===2)return '⚔️ Liguilla';return '—'}}if(pos===1)return '🏆 Copa Regional';if(pos>=2&&pos<=5)return '⚔️ Liguilla';return '—'}
  function generalStatus(pos,total,competitionName){const champion=pos===1?'🏅 Campeón general':'';if(!isAfacon())return champion||'—';const c=norm(competitionName);let extra='';if(c.includes('liga a')){if(pos===Math.max(1,total-2))extra='⚠️ Repechaje permanencia';if(pos>=Math.max(1,total-1))extra='⬇️ Descenso a Liga B'}else if(c.includes('liga b')){if(pos===1||pos===2)extra='⬆️ Ascenso a Liga A';else if(pos===3)extra='⚠️ Repechaje ascenso'}return [champion,extra].filter(Boolean).join(' · ')||'—'}
  function selectedSeriesName(body){const pub=body?.id==='pubStandings',id=document.querySelector(pub?'#pubSeries':'#series')?.value;return S.series.find(x=>x.id===id)?.name||''}
  function selectedCompetitionName(body){const pub=body?.id==='pubStandings',id=document.querySelector(pub?'#pubCompetition':'#competition')?.value;return S.comps.find(x=>x.id===id)?.name||''}
  function decorateSeriesTable(body){if(!body)return;const table=body.closest('table'),head=table?.querySelector('thead tr');if(!head)return;if(!head.querySelector('[data-qualification]')){const th=document.createElement('th');th.dataset.qualification='1';th.textContent='Situación';head.appendChild(th)}const rows=[...body.querySelectorAll('tr')],seriesName=selectedSeriesName(body),competitionName=selectedCompetitionName(body);rows.forEach(r=>{const cells=r.querySelectorAll('td');if(!cells.length)return;const pos=Number(cells[0].textContent);if(!Number.isFinite(pos))return;let td=r.querySelector('[data-qualification]');if(!td){td=document.createElement('td');td.dataset.qualification='1';r.appendChild(td)}td.innerHTML=`<b>${seriesQualificationStatus(pos,seriesName,competitionName)}</b>`});const wrap=table.closest('.table')?.parentElement;let note=wrap?.querySelector('[data-series-qualification-note]');if(wrap&&!note){note=document.createElement('p');note.dataset.seriesQualificationNote='1';note.className='muted';table.closest('.table').after(note)}if(note){if(isInternalOnlySeries(seriesName))note.textContent='Esta serie define solo campeón interno; no entrega cupo a Copa Regional ni liguilla regional.';else if(isAfacon()&&norm(competitionName).includes('liga a'))note.textContent='Afacon Liga A: el 1° de la serie va a Copa Regional; el 2° y 3° van a liguilla.';else if(isAfacon()&&norm(competitionName).includes('liga b'))note.textContent='Afacon Liga B: el 1° y 2° de la serie van a liguilla contra los 2 clasificados de Liga A.';else note.textContent='Clasificación provisoria de esta serie: el 1° va a Copa Regional y del 2° al 5° están en zona de liguilla.'}}
  function decoratePublicGeneral(){const body=document.querySelector('#pubGeneral');if(!body)return;const table=body.closest('table'),head=table?.querySelector('thead tr');if(!head)return;if(!head.querySelector('[data-qualification]')){const th=document.createElement('th');th.dataset.qualification='1';th.textContent='Situación';head.appendChild(th)}const rows=[...body.querySelectorAll('tr')],comp=S.comps.find(x=>x.id===document.querySelector('#pubCompetition')?.value);rows.forEach(r=>{const cells=r.querySelectorAll('td');if(!cells.length)return;const pos=Number(cells[0].textContent);if(!Number.isFinite(pos))return;let td=r.querySelector('[data-qualification]');if(!td){td=document.createElement('td');td.dataset.qualification='1';r.appendChild(td)}td.innerHTML=`<b>${generalStatus(pos,rows.length,comp?.name)}</b>`});const card=table.closest('.card');if(card){let note=card.querySelector('#qualificationNote');if(!note){note=document.createElement('p');note.id='qualificationNote';note.className='muted';card.querySelector('h3')?.after(note)}const c=norm(comp?.name);note.textContent=isAfacon()?(c.includes('liga a')?'Tabla general Afacon Liga A: el 1° figura como campeón general; los 2 últimos están en zona de descenso y el antepenúltimo en repechaje.':c.includes('liga b')?'Tabla general Afacon Liga B: el 1° figura como campeón general; los 2 primeros están en zona de ascenso a Liga A y el 3° en zona de repechaje.':'El 1° figura como campeón general.'):'El 1° de la tabla general figura como campeón general.'}}
  function ensureAdminGeneral(){const panel=document.querySelector('#p-tables');if(!panel||document.querySelector('#adminGeneralCard'))return;const card=document.createElement('div');card.id='adminGeneralCard';card.className='card';card.style.marginTop='16px';card.innerHTML='<h3>Tabla general acumulada</h3><p id="adminQualificationNote" class="muted"></p><div class="table"><table><thead><tr><th>POS</th><th>Equipo</th><th>PTS</th><th>Situación</th></tr></thead><tbody id="adminGeneral"></tbody></table></div>';panel.appendChild(card)}
  let generalTimer;async function loadAdminGeneral(){ensureAdminGeneral();const body=document.querySelector('#adminGeneral');if(!body||!S.u)return;const cid=document.querySelector('#competition')?.value;if(!cid){body.innerHTML='<tr><td colspan="4">Sin datos disponibles.</td></tr>';return}const comp=S.comps.find(x=>x.id===cid),{data,error}=await sb.rpc('get_general_standings',{p_competition_id:cid});if(error){body.innerHTML=`<tr><td colspan="4">${error.message}</td></tr>`;return}const list=data||[];body.innerHTML=list.map(x=>`<tr><td>${x.pos}</td><td>${x.team_name}</td><td><b>${x.pts}</b></td><td><b>${generalStatus(Number(x.pos),list.length,comp?.name)}</b></td></tr>`).join('')||'<tr><td colspan="4">Sin datos disponibles.</td></tr>';const note=document.querySelector('#adminQualificationNote');if(note){const c=norm(comp?.name);note.textContent=isAfacon()?(c.includes('liga a')?'Afacon Liga A: campeón general, descenso y repechaje según tabla general.':c.includes('liga b')?'Afacon Liga B: campeón general; los 2 primeros ascienden a Liga A y el 3° juega repechaje.':'Campeón general según tabla general.'):'El 1° de la tabla general figura como campeón general.'}}
  function scheduleAdminGeneral(){clearTimeout(generalTimer);generalTimer=setTimeout(loadAdminGeneral,120)}
  function installQualificationViews(){decorateSeriesTable(document.querySelector('#pubStandings'));decorateSeriesTable(document.querySelector('#standings'));decoratePublicGeneral();ensureAdminGeneral();scheduleAdminGeneral();const pubSeriesBody=document.querySelector('#pubStandings');if(pubSeriesBody&&!pubSeriesBody.dataset.qualWatch){pubSeriesBody.dataset.qualWatch='1';new MutationObserver(()=>decorateSeriesTable(pubSeriesBody)).observe(pubSeriesBody,{childList:true})}const adminSeriesBody=document.querySelector('#standings');if(adminSeriesBody&&!adminSeriesBody.dataset.qualWatch){adminSeriesBody.dataset.qualWatch='1';new MutationObserver(()=>{decorateSeriesTable(adminSeriesBody);scheduleAdminGeneral()}).observe(adminSeriesBody,{childList:true})}const pubGen=document.querySelector('#pubGeneral');if(pubGen&&!pubGen.dataset.qualWatch){pubGen.dataset.qualWatch='1';new MutationObserver(()=>decoratePublicGeneral()).observe(pubGen,{childList:true})}const pc=document.querySelector('#pubCompetition');if(pc&&!pc.dataset.qualWatch){pc.dataset.qualWatch='1';pc.addEventListener('change',()=>setTimeout(()=>{decorateSeriesTable(pubSeriesBody);decoratePublicGeneral()},150))}const ps=document.querySelector('#pubSeries');if(ps&&!ps.dataset.qualWatch){ps.dataset.qualWatch='1';ps.addEventListener('change',()=>setTimeout(()=>decorateSeriesTable(pubSeriesBody),150))}const ac=document.querySelector('#competition');if(ac&&!ac.dataset.qualWatch){ac.dataset.qualWatch='1';ac.addEventListener('change',()=>{setTimeout(()=>decorateSeriesTable(adminSeriesBody),120);scheduleAdminGeneral()})}const as=document.querySelector('#series');if(as&&!as.dataset.qualWatch){as.dataset.qualWatch='1';as.addEventListener('change',()=>setTimeout(()=>decorateSeriesTable(adminSeriesBody),120))}}

  let reportCache=new Map(),archiveTimer;
  function ensureReportModal(){if(document.querySelector('#reportHistoryModal'))return;const modal=document.createElement('div');modal.id='reportHistoryModal';modal.className='modal hidden';modal.innerHTML=`<div class="card modal-card" style="width:min(760px,100%);max-height:85vh;overflow:auto"><div class="fixture-head"><h2 style="margin:0">Informe arbitral</h2><button id="closeReportHistory" class="ghost">✕</button></div><div id="reportHistoryBody" style="display:grid;gap:12px;margin-top:14px"></div></div>`;document.body.appendChild(modal);modal.querySelector('#closeReportHistory').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')}}
  async function showReportHistory(matchId){ensureReportModal();const modal=document.querySelector('#reportHistoryModal'),body=document.querySelector('#reportHistoryBody');modal.classList.remove('hidden');body.innerHTML='<div class="empty">Cargando informe...</div>';let list=reportCache.get(matchId);if(!list){const {data,error}=await sb.from('arbitral_reports').select('id,match_id,report_text,document_url,created_at').eq('match_id',matchId).order('created_at',{ascending:false});if(error){body.innerHTML=`<div class="msg error">${error.message}</div>`;return}list=data||[];reportCache.set(matchId,list)}if(!list.length){body.innerHTML='<div class="empty">Este partido no tiene informe arbitral guardado.</div>';return}body.innerHTML='';for(const r of list){const card=document.createElement('div');card.className='card';const when=r.created_at?new Date(r.created_at).toLocaleString('es-CL'):'';card.innerHTML=`<p class="muted" style="margin-top:0">${when}</p><pre style="white-space:pre-wrap;font:inherit;background:#c7d6ca;padding:12px;border-radius:10px">${r.report_text||'Sin observaciones escritas.'}</pre>`;if(r.document_url){const {data:signed}=await sb.storage.from('match-files').createSignedUrl(r.document_url,300);if(signed?.signedUrl){const a=document.createElement('a');a.href=signed.signedUrl;a.target='_blank';a.rel='noopener';a.className='primary';a.style='display:inline-block;text-decoration:none;padding:8px 12px;border-radius:10px;margin-top:8px';a.textContent='Ver foto / PDF';card.appendChild(a)}}body.appendChild(card)}}
  function adminFixtureList(){const cid=document.querySelector('#fCompetition')?.value;let list=S.fixtures.filter(f=>f.competition_id===cid);if(S.u?.role==='team_admin')list=list.filter(f=>[f.home?.id,f.away?.id].includes(S.u.team_id));return list}
  function ensureFixtureFilters(){const panel=document.querySelector('#p-fixtures'),fixtures=document.querySelector('#fixtures');if(!panel||!fixtures||document.querySelector('#fixtureArchiveFilters'))return;const box=document.createElement('div');box.id='fixtureArchiveFilters';box.className='card';box.style='margin:14px 0';box.innerHTML=`<div class="section-title"><div><h3 style="margin:0">Buscar fechas anteriores</h3><p class="muted" style="margin:5px 0 0">Filtra por número de fecha o por día y abre los informes guardados desde cada partido.</p></div><button id="clearFixtureArchiveFilters" class="ghost small">Mostrar todas</button></div><div class="filters" style="margin-top:12px"><label>Fecha N°<select id="fixtureRoundFilter"><option value="">Todas</option></select></label><label>Día<input id="fixtureDateFilter" type="date"></label></div>`;fixtures.before(box);box.querySelector('#fixtureRoundFilter').onchange=applyFixtureFilters;box.querySelector('#fixtureDateFilter').onchange=applyFixtureFilters;box.querySelector('#clearFixtureArchiveFilters').onclick=()=>{box.querySelector('#fixtureRoundFilter').value='';box.querySelector('#fixtureDateFilter').value='';applyFixtureFilters()}}
  function refreshFixtureFilterOptions(list){const sel=document.querySelector('#fixtureRoundFilter');if(!sel)return;const current=sel.value,rounds=[...new Set(list.map(f=>f.round_number).filter(x=>x!==null&&x!==undefined))].sort((a,b)=>a-b);sel.innerHTML='<option value="">Todas</option>'+rounds.map(r=>`<option value="${r}">Fecha ${r}</option>`).join('');if(rounds.map(String).includes(current))sel.value=current}
  function applyFixtureFilters(){const round=document.querySelector('#fixtureRoundFilter')?.value||'',date=document.querySelector('#fixtureDateFilter')?.value||'';document.querySelectorAll('#fixtures .fixture[data-fixture-id]').forEach(card=>{const okRound=!round||card.dataset.round===round,okDate=!date||card.dataset.date===date;card.classList.toggle('hidden',!(okRound&&okDate))})}
  async function decorateFixtureArchive(){if(!S.u)return;ensureFixtureFilters();ensureReportModal();const list=adminFixtureList(),cards=[...document.querySelectorAll('#fixtures .fixture')];refreshFixtureFilterOptions(list);const matchIds=[];cards.forEach((card,i)=>{const f=list[i];if(!f)return;card.dataset.fixtureId=f.id;card.dataset.round=f.round_number==null?'':String(f.round_number);card.dataset.date=f.fixture_date||'';const matches=S.matches.filter(m=>m.club_fixture_id===f.id),rows=[...card.querySelectorAll('.series-row')];rows.forEach((row,j)=>{const m=matches[j];if(!m)return;row.dataset.matchId=m.id;matchIds.push(m.id)})});if(matchIds.length){const {data}=await sb.from('arbitral_reports').select('id,match_id,report_text,document_url,created_at').in('match_id',matchIds).order('created_at',{ascending:false});reportCache=new Map();for(const r of data||[]){if(!reportCache.has(r.match_id))reportCache.set(r.match_id,[]);reportCache.get(r.match_id).push(r)}}cards.forEach(card=>card.querySelectorAll('.series-row').forEach(row=>{const id=row.dataset.matchId;if(!id)return;let actions=row.querySelector('[data-match-actions]');const manage=row.querySelector('button[onclick*="manageMatch"]');if(!actions){actions=document.createElement('span');actions.dataset.matchActions='1';actions.style='display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end';if(manage){manage.replaceWith(actions);actions.appendChild(manage)}else row.appendChild(actions)}let btn=actions.querySelector('[data-report-history]');const has=(reportCache.get(id)||[]).length>0;if(has&&!btn){btn=document.createElement('button');btn.type='button';btn.className='primary small';btn.dataset.reportHistory='1';btn.textContent='Ver informe arbitral';btn.onclick=()=>showReportHistory(id);actions.appendChild(btn)}if(!has&&btn)btn.remove()}));applyFixtureFilters()}
  function scheduleFixtureArchive(){clearTimeout(archiveTimer);archiveTimer=setTimeout(decorateFixtureArchive,140)}
  function installFixtureArchive(){ensureFixtureFilters();ensureReportModal();const host=document.querySelector('#fixtures');if(host&&!host.dataset.archiveWatch){host.dataset.archiveWatch='1';new MutationObserver(scheduleFixtureArchive).observe(host,{childList:true,subtree:true})}const comp=document.querySelector('#fCompetition');if(comp&&!comp.dataset.archiveWatch){comp.dataset.archiveWatch='1';comp.addEventListener('change',()=>{reportCache.clear();setTimeout(scheduleFixtureArchive,180)})}scheduleFixtureArchive()}

  function init(){if(!waitForApp())return setTimeout(init,100);ensurePanels();installAdminGate();installManualVenue();installQualificationViews();installFixtureArchive();const nav=document.querySelector('#nav');new MutationObserver(()=>{ensurePanels();patchNav();installManualVenue();installQualificationViews();installFixtureArchive()}).observe(nav,{childList:true});setInterval(()=>{decorateSeriesTable(document.querySelector('#pubStandings'));decoratePublicGeneral();if(!document.querySelector('#adminView').classList.contains('hidden')){patchNav();installManualVenue();installQualificationViews();installFixtureArchive()}},900)}
  init();
})();