(()=>{
const FENFUR_VALUE='__fenfur_admin__';
const css=`#p-fenfur-live{max-width:1260px;margin:auto}.fenfur-admin-head{background:linear-gradient(135deg,#26070a,#6f0d13);color:#fff;border-top:5px solid #d5ae42}.fenfur-admin-head h2{color:#fff;margin:0 0 6px}.fenfur-admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:14px}.fenfur-admin-card{background:linear-gradient(180deg,#2b0b0e,#1f0709);color:#fff;border:1px solid #6f2b2f;border-radius:15px;padding:14px}.fenfur-admin-card h3{color:#fff;margin:0}.fenfur-admin-card small{color:#dcbfc1}.fenfur-admin-row{display:grid;grid-template-columns:1fr 80px 80px;gap:8px;align-items:end;margin-top:10px}.fenfur-admin-row input,.fenfur-admin-row select{background:#421116;color:#fff;border-color:#7b3438}.fenfur-admin-card .primary{background:linear-gradient(135deg,#a8121d,#6f0d13);border:1px solid #d5ae42}.fenfur-status{margin-top:8px;color:#f2d67d;font-weight:900}@media(max-width:760px){.fenfur-admin-grid{grid-template-columns:1fr}.fenfur-admin-row{grid-template-columns:1fr 72px 72px}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
let category='Senior 35';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function openFenfur(){const panel=document.querySelector('#p-fenfur-live'),btn=document.querySelector('#navFenfurLive');if(!panel)return;document.querySelectorAll('#adminView .panel').forEach(p=>p.classList.add('hidden'));document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('active'));panel.classList.remove('hidden');btn?.classList.add('active');load()}
function ensureAdminOption(){const sel=document.querySelector('#ownerAssociation');if(!sel)return;let opt=[...sel.options].find(o=>o.value===FENFUR_VALUE);if(!opt){opt=document.createElement('option');opt.value=FENFUR_VALUE;opt.textContent='🏆 FENFUR · COPA REGIONAL';sel.appendChild(opt)}if(!sel.dataset.fenfurAdminBound){sel.dataset.fenfurAdminBound='1';sel.addEventListener('change',e=>{if(sel.value===FENFUR_VALUE){e.stopImmediatePropagation();openFenfur()}},true)}}
function build(){const admin=document.querySelector('#adminView'),main=admin?.querySelector('main'),nav=document.querySelector('#nav');if(!admin||!main||!nav)return;ensureAdminOption();if(document.querySelector('#p-fenfur-live'))return;
 const panel=document.createElement('section');panel.id='p-fenfur-live';panel.className='panel hidden';panel.innerHTML=`<div class="card fenfur-admin-head"><h2>🏆 Copa Regional FENFUR · Resultados en vivo</h2><p style="margin:0;color:#f0d5d7">Gestión de resultados de la Copa Regional.</p><div class="filters" style="margin-top:14px"><label style="color:#fff">Serie<select id="fenfurAdminCategory"><option>Senior 35</option><option>Senior 50</option></select></label></div></div><div id="fenfurAdminGrid" class="fenfur-admin-grid"></div>`;main.appendChild(panel);
 const btn=document.createElement('button');btn.id='navFenfurLive';btn.textContent='🏆 Copa Regional';btn.onclick=openFenfur;nav.appendChild(btn);panel.querySelector('#fenfurAdminCategory').onchange=e=>{category=e.target.value;load()};
}
async function load(){const grid=document.querySelector('#fenfurAdminGrid');if(!grid||typeof sb==='undefined')return;grid.innerHTML='<div class="card">Cargando partidos autorizados…</div>';const {data,error}=await sb.rpc('get_fenfur_admin_ties',{p_category:category});if(error){grid.innerHTML=`<div class="card"><b>No se pudo cargar Copa Regional.</b><div class="msg error">${esc(error.message)}</div></div>`;return}const rows=data||[];if(!rows.length){grid.innerHTML='<div class="card">No tienes partidos asignados en esta categoría.</div>';return}grid.innerHTML=rows.map(x=>card(x)).join('');grid.querySelectorAll('[data-save]').forEach(b=>b.onclick=save)}
function card(x){const g=v=>v==null?'':v;return `<article class="fenfur-admin-card" data-tie="${x.id}"><div class="fixture-head"><div><small>${esc(x.category)} · Llave ${esc(x.tie_order)}</small><h3>${esc(x.home_team)} vs ${esc(x.away_team)}</h3></div><span class="fenfur-status">${esc(x.status||'Programación')}</span></div><div class="fenfur-admin-row"><label style="color:#fff">IDA<select data-status-1><option ${x.status==='Programación'?'selected':''}>Programación</option><option ${x.status==='En vivo'?'selected':''}>En vivo</option><option ${x.status==='Finalizado'?'selected':''}>Finalizado</option></select></label><label style="color:#fff">${esc(x.home_team)}<input data-h1 type="number" min="0" value="${g(x.first_leg_home_goals)}"></label><label style="color:#fff">${esc(x.away_team)}<input data-a1 type="number" min="0" value="${g(x.first_leg_away_goals)}"></label></div><div class="actions"><button class="primary small" data-save data-leg="1">Guardar ida</button></div><div class="fenfur-admin-row"><label style="color:#fff">VUELTA<select data-status-2><option>Programación</option><option>En vivo</option><option>Finalizado</option></select></label><label style="color:#fff">${esc(x.away_team)}<input data-h2 type="number" min="0" value="${g(x.second_leg_home_goals)}"></label><label style="color:#fff">${esc(x.home_team)}<input data-a2 type="number" min="0" value="${g(x.second_leg_away_goals)}"></label></div><div class="actions"><button class="primary small" data-save data-leg="2">Guardar vuelta</button></div><div class="msg" data-msg></div></article>`}
async function save(e){const b=e.currentTarget,card=b.closest('[data-tie]'),leg=Number(b.dataset.leg),msg=card.querySelector('[data-msg]');const hg=Number(card.querySelector(leg===1?'[data-h1]':'[data-h2]').value),ag=Number(card.querySelector(leg===1?'[data-a1]':'[data-a2]').value),status=card.querySelector(leg===1?'[data-status-1]':'[data-status-2]').value;if(!Number.isInteger(hg)||hg<0||!Number.isInteger(ag)||ag<0){msg.className='msg error';msg.textContent='Ingresa un marcador válido.';return}b.disabled=true;msg.className='msg';msg.textContent='Guardando…';const {error}=await sb.rpc('update_fenfur_live_result',{p_tie_id:Number(card.dataset.tie),p_leg:leg,p_home_goals:hg,p_away_goals:ag,p_status:status});b.disabled=false;if(error){msg.className='msg error';msg.textContent=error.message;return}msg.className='msg ok';msg.textContent='Resultado actualizado.';setTimeout(()=>msg.textContent='',1800)}
function init(){if(typeof sb==='undefined'||!document.querySelector('#adminView'))return setTimeout(init,150);build();ensureAdminOption();const sel=document.querySelector('#ownerAssociation');if(sel)new MutationObserver(()=>ensureAdminOption()).observe(sel,{childList:true});const mo=new MutationObserver(()=>{build();ensureAdminOption()});mo.observe(document.querySelector('#adminView'),{attributes:true,subtree:true,childList:true})}init();
})();