(()=>{
const css=`
#fenfurCup{margin:18px 0 26px;background:linear-gradient(145deg,#190608,#39090d 55%,#170506);color:#fff;border:1px solid #7b2529;border-top:5px solid #d5ae42;border-radius:20px;overflow:hidden;box-shadow:0 18px 42px rgba(38,0,3,.28)}
.fenfur-hero{padding:22px;background:radial-gradient(circle at 85% 10%,rgba(213,174,66,.2),transparent 35%)}.fenfur-kicker{color:#e0bd57;font-size:.72rem;font-weight:950;letter-spacing:.18em}.fenfur-title{color:#fff;margin:6px 0 3px;font-size:1.7rem}.fenfur-sub{color:#e6c9ca;margin:0;font-weight:800}.fenfur-tabs{display:flex;gap:8px;padding:0 22px 18px}.fenfur-tab{background:#531116;color:#f4d7d8;border:1px solid #7e3034}.fenfur-tab.active{background:linear-gradient(135deg,#b41620,#761016);color:#fff;border-color:#e1b74d;box-shadow:0 0 0 2px rgba(225,183,77,.15)}.fenfur-body{padding:0 22px 22px}.fenfur-phase{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:0 0 12px}.fenfur-phase h3{color:#fff;margin:0}.fenfur-count{color:#e0bd57;font-size:.8rem;font-weight:900}.fenfur-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.fenfur-tie{background:linear-gradient(180deg,#2b0b0e,#20080a);border:1px solid #6e292d;border-radius:15px;padding:14px;box-shadow:0 8px 20px rgba(0,0,0,.2)}.fenfur-tiehead{display:flex;justify-content:space-between;gap:8px;color:#d9b84f;font-size:.7rem;font-weight:950;letter-spacing:.08em;margin-bottom:9px}.fenfur-team{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:9px 10px;background:#3a1014;border-radius:9px;margin-top:6px;font-weight:950}.fenfur-team small{display:block;color:#d8bfc0;font-weight:750}.fenfur-vs{text-align:center;color:#d5ae42;font-size:.72rem;font-weight:950;margin:5px}.fenfur-meta{margin-top:10px;border-top:1px solid #5d2529;padding-top:9px;color:#d7bfc0;font-size:.78rem;font-weight:800}.fenfur-empty{padding:25px;text-align:center;border:1px dashed #7e3034;border-radius:14px;color:#e4cacc}.fenfur-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:#d5ae42;color:#281006;font-size:.68rem;font-weight:950}.fenfur-admin-note{margin-top:13px;padding:11px;border:1px solid #72511f;background:#2d210c;color:#f0d98d;border-radius:11px;font-size:.8rem;font-weight:850}@media(max-width:700px){.fenfur-grid{grid-template-columns:1fr}.fenfur-title{font-size:1.35rem}.fenfur-hero,.fenfur-body{padding-left:15px;padding-right:15px}.fenfur-tabs{padding-left:15px;padding-right:15px}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
let category='Senior 35';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensure(){const host=document.querySelector('.public-main');if(!host||document.querySelector('#fenfurCup'))return;const box=document.createElement('section');box.id='fenfurCup';box.innerHTML=`<div class="fenfur-hero"><div class="fenfur-kicker">FENFUR · REGIÓN DEL MAULE</div><h2 class="fenfur-title">🏆 COPA REGIONAL 2026</h2><p class="fenfur-sub">La competencia regional, ahora en Linares Score.</p></div><div class="fenfur-tabs"><button class="fenfur-tab active" data-cat="Senior 35">SERIE 35</button><button class="fenfur-tab" data-cat="Senior 50">SERIE 50</button></div><div class="fenfur-body"><div class="fenfur-phase"><h3>Dieciseisavos de final</h3><span class="fenfur-count" id="fenfurCount"></span></div><div id="fenfurGrid" class="fenfur-grid"><div class="fenfur-empty">Cargando Copa Regional…</div></div><div class="fenfur-admin-note">⚡ Diseñado para seguimiento rápido de llaves de ida y vuelta. Los datos pendientes se mostrarán como “Por definir”.</div></div>`;host.prepend(box);box.querySelectorAll('.fenfur-tab').forEach(b=>b.onclick=()=>{category=b.dataset.cat;box.querySelectorAll('.fenfur-tab').forEach(x=>x.classList.toggle('active',x===b));load()});load()}
async function load(){const grid=document.querySelector('#fenfurGrid'),count=document.querySelector('#fenfurCount');if(!grid||typeof sb==='undefined')return;grid.innerHTML='<div class="fenfur-empty">Cargando llaves…</div>';const {data,error}=await sb.from('fenfur_ties').select('*').eq('category',category).order('tie_order');if(error){grid.innerHTML='<div class="fenfur-empty">La Copa Regional está preparándose.</div>';return}const rows=data||[];count.textContent=rows.length?`${rows.length} llaves`:'';if(!rows.length){grid.innerHTML=`<div class="fenfur-empty"><b>${esc(category)}</b><br>Fixture oficial listo para ser incorporado. Programación detallada por confirmar.</div>`;return}grid.innerHTML=rows.map((x,i)=>`<article class="fenfur-tie"><div class="fenfur-tiehead"><span>LLAVE ${esc(x.tie_order||i+1)}</span><span class="fenfur-badge">${esc(x.status||'Programación')}</span></div><div class="fenfur-team"><span>${esc(x.home_team)}<small>${esc(x.home_association||'')}</small></span></div><div class="fenfur-vs">VS</div><div class="fenfur-team"><span>${esc(x.away_team)}<small>${esc(x.away_association||'')}</small></span></div><div class="fenfur-meta">IDA · ${esc(x.first_leg_date||'Fecha por definir')} · ${esc(x.first_leg_time||'Hora por definir')} · ${esc(x.first_leg_venue||'Cancha por definir')}<br>VUELTA · ${esc(x.second_leg_date||'Fecha por definir')} · ${esc(x.second_leg_time||'Hora por definir')} · ${esc(x.second_leg_venue||'Cancha por definir')}</div></article>`).join('')}
function init(){if(typeof sb==='undefined'||!document.querySelector('.public-main'))return setTimeout(init,120);ensure()}init();
})();